### ISSUE TITLE
Missing "created" property in "createfolderifnotexists" method

### ISSUE THREAD

**Issue by tobihagemann** [pCloud/pcloud-sdk-swift#13]
First of all, thank you for the quick release of 3.1.0 and even including the [`createfolderifnotexists`](https://docs.pcloud.com/methods/folder/createfolderifnotexists.html) API method that I would like to use as well. :+1:

However, I'm missing the `created` property (not the one inside `metadata`), which tells if the folder has been created or not (boolean). For my use case, I'd like to know if the folder already existed after calling this method.

**Comment by tmpit** [comment]
Yeah, that field should be added. I guess I missed it in the docs.
