### ISSUE TITLE
Fatal error: Unable to bridge NSNumber to Int - when parsing audio metadata.

### ISSUE THREAD

**Issue by leshkoapps** [pCloud/pcloud-sdk-swift#19]
1. Upload example.mp3 from example.mp3.zip to "Test" folder on your account.
2. Run Example_iOS on iOS simulator. 
3. Open "Test" folder.
4. Fatal error: Unable to bridge NSNumber to Int. 
<img width="1512" alt="Screen Shot 2022-08-31 at 21 03 57" src="https://user-images.githubusercontent.com/10809541/187762926-23c883d2-95aa-408b-b381-10a910e6a352.png">

**Resources:**
[example.mp3.zip](https://github.com/pCloud/pcloud-sdk-swift/files/9464344/example.mp3.zip)

**Comment by tmpit** [comment]
This issue was fixed in 3.0.1, but the version of the SDK in the example project is 3.0.0. It hasn't been updated recently. Could you run a `pod update` and try again?

**Comment by leshkoapps** [comment]
Thanks! This helps.
