### ISSUE TITLE
Crash on file upload

### ISSUE THREAD

**Issue by demoszp** [pCloud/pcloud-sdk-swift#22]
Hello, team
if the uploaded file has modification date older than 1 January 1970, than SDK produces crash on this line of code
PCloudAPI.swift:620
`parameters.append(.number(name: "mtime", value: UInt64(modificationDate.timeIntervalSince1970)))`
crash occurs  because timeIntervalSince1970 return negative number for such date
Will be glad if you can fix this

**Comment by tmpit** [comment]
Hey, I'll take a look at it on the 9th. I think I'll just trim the value to 0. Better to bitcast and end up with garbage.

**Comment by tmpit** [comment]
Released in 3.2.2.
