### ISSUE TITLE
Uploading a zero-byte file

### ISSUE THREAD

**Issue by demoszp** [pCloud/pcloud-sdk-swift#24]
Hi team,
When uploading a zero-byte file using the method
PCloudClient.upload(fromFileAt, toFolder, asFileNamed),
the file is uploaded to the server, but the method returns the error NSURLErrorDomain/NSURLErrorTimedOut.
I suppose that upon a successful upload, the method should not return an error.

**Comment by tmpit** [comment]
Hey, I'll take a look and will probably have more information tomorrow.

**Comment by tmpit** [comment]
Seems to be a server issue. I'm forwarding this to our back end team and will get back to you when I have a response.

**Comment by tmpit** [comment]
It seems this won't be fixed in a timely manner. The only thing I can recommend is to work around the issue by using the `createUpload()`, `getUploadInfo()`, `upload(*,toUpload:)`, `saveUpload()` family of methods on the `PCloudClient`. It is a bit more involved but allows for more flexibility.

**Comment by wws13** [comment]
can you give me a code example for this work around, if I call createUpload and upload(Data(),toUpload:uploadId) I receive same NSURLErrorTimedOut error, if createUpload and then saveUpload (without upload(*,toUpload:)) it crashed in PCloudSDKSwift
