### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by Alex-C-Eltima** [pCloud/pcloud-sdk-swift#3]
Hello,

We are trying to use your SDK to include pCloud support into our CloudMounter app. Unfortunately, if Two-factor authentication is enabled for the account, we do not receive any authentication form for confirmation code. Could you please let me know how we can proceed with 2FA accounts using this SDK?

**Comment by tmpit** [comment]
Hello,

This isn't a problem with the SDK itself. Currently our OAuth implementation does not allow users with 2FA to log in. I spoke to our web team about this. This is planned to be implemented within the next two months.

**Comment by Alex-C-Eltima** [comment]
Thank you for reply.

**Comment by Alex-C-Eltima** [comment]
It has been a while since your reply regarding two months implementation of 2FA support, is there any progress in this question?

**Comment by tmpit** [comment]
This should have been released a while ago. I'll check with our web team.

**Comment by tmpit** [comment]
Support will be added by the end of next week.

**Comment by sich** [comment]
Hello @Alex-C-Eltima, I'm from the web team. There is slight delay with the fix. We fixed it, but the release is scheduled for Monday. Will write again once released.

**Comment by sich** [comment]
The release is deployed.
