### ISSUE TITLE
If uploaded file name contains "&" character all further symbols are ignored 

### ISSUE THREAD

**Issue by Alex-C-Eltima** [pCloud/pcloud-sdk-swift#4]
Hello,

We are trying to use your SDK to include pCloud support into our CloudMounter app. Upon file upload using the following method of PCloudClient class

func upload(fromFileAt path: URL, toFolder folderId: UInt64, asFileNamed name: String, withModificationDate date: Date? = nil) -> UploadTask<PCloudAPI.UploadFile>

if the initial file name contains "&" character, all subsequent symbols are cut off in the name of uploaded file. 

Kindly take a look.

**Comment by tmpit** [comment]
Hey, I'm looking into it. It seems I am relying on `URLComponents.query` property for encoding when it comes to upload tasks, but this does not work for valid URL characters (such as "&") within query item values.

**Comment by tmpit** [comment]
Will submit a new version later today.

**Comment by Alex-C-Eltima** [comment]
Hey, thanks, all is working correctly now
