### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by tobihagemann** [pCloud/pcloud-sdk-swift#8]
In my opinion, Swift Package Manager is becoming the dominant dependency management solution for Swift projects. Are there any plans to support SPM for this library?

**Comment by tmpit** [comment]
Hey. We are definitely going to add support for it at some point, but we don't have any concrete plans as to exactly when. Do you need SPM support for your project?

**Comment by tobihagemann** [comment]
Not immediately. We just added support for pCloud in our Android app and we're now exploring our options for the iOS app as well.

**Comment by tmpit** [comment]
I should be able to add support for SPM by the start of next week.
